---
name: Python Semantic Release - Publish

description: Publish Artifacts & Assets to GitHub Releases

branding:
  icon: upload
  color: orange

inputs:
  directory:
    description: |
      Sub-directory to change into before running semantic-release publish
    default: "."
    required: false

  github_token:
    description: |
      GitHub token used to upload artifacts. Requires permission to create and
      edit releases.
    required: true
    default: ${{ github.token }}

  root_options:
    description: |
      Additional options for the root `semantic-release` command.
      Example: -vv --noop
    required: false
    default: "-v"

  tag:
    description: |
      The tag corresponding to the GitHub Release that the artifacts should
      be published to. Defaults to 'latest', in which case the latest tag
      will be identified by Python Semantic Release and used to publish to.
    required: false

runs:
  using: docker
  image: src/Dockerfile
