name: Validation Pipeline

on:
  # Enable workflow as callable from other workflow
  workflow_call:
    # inputs: none required ATT
    # outputs: none required ATT
    # secrets: none required ATT


# set default Token permissions = none
permissions: {}


jobs:

  eval-changes:
    name: Evaluate changes
    runs-on: ubuntu-latest

    steps:
      - name: Setup | Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          fetch-depth: 50 # Must at least retrieve a set of commits to compare changes
          # primarily because of any 'Rebase and Merge' PR action in GitHub

      - name: Evaluate | Check specific file types for changes
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c  # v46.0.5
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        with:
          base_sha: ${{ github.event.push.before || github.event.pull_request.base.sha }}
          # action.yml is not considered as src because we can't test it
          files_yaml: |
            ci:
              - .github/workflows/validate.yml
              - .github/workflows/ci.yml
            docs:
              - AUTHORS.rst
              - CONTRIBUTING.rst
              - LICENSE
              - README.md
            src:
              - src/**
            tests:
              - tests/**

      - name: Evaluate | Detect if any of the combinations of file sets have changed
        id: all-changes
        if: ${{ steps.changed-files.outcome == 'success' }}
        run: |
          printf '%s\n' "any_changed=false" >> $GITHUB_OUTPUT
          if [ "${{ steps.changed-files.outputs.ci_any_changed }}" == "true" ] || \
              [ "${{ steps.changed-files.outputs.docs_any_changed }}" == "true" ] || \
              [ "${{ steps.changed-files.outputs.src_any_changed }}" == "true" ] || \
              [ "${{ steps.changed-files.outputs.tests_any_changed }}" == "true" ]; then
              printf '%s\n' "any_changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Evaluate | Handle manual trigger (lie that all files changed)
        id: manual-trigger
        if: github.event_name == 'workflow_dispatch'
        run: |
          printf '%s\n' "ci_any_changed=true" >> $GITHUB_OUTPUT
          printf '%s\n' "docs_any_changed=true" >> $GITHUB_OUTPUT
          printf '%s\n' "src_any_changed=true" >> $GITHUB_OUTPUT
          printf '%s\n' "tests_any_changed=true" >> $GITHUB_OUTPUT
          printf '%s\n' "any_changed=true" >> $GITHUB_OUTPUT

    outputs:
      any-file-changes: ${{ steps.all-changes.outputs.any_changed || steps.manual-trigger.outputs.any_changed }}
      ci-changes: ${{ steps.changed-files.outputs.ci_any_changed || steps.manual-trigger.outputs.ci_any_changed }}
      doc-changes: ${{ steps.changed-files.outputs.docs_any_changed || steps.manual-trigger.outputs.docs_any_changed }}
      src-changes: ${{ steps.changed-files.outputs.src_any_changed || steps.manual-trigger.outputs.src_any_changed }}
      test-changes: ${{ steps.changed-files.outputs.tests_any_changed || steps.manual-trigger.outputs.tests_any_changed }}


  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Setup | Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}

      - name: Validate | Commitlint
        uses: wagoid/commitlint-github-action@b948419dd99f3fd78a6548d48f94e3df7f6bf3ed  # v6.2.1


  validate-action:
    name: Validate Action Build & Execution
    runs-on: ubuntu-latest
    if: needs.eval-changes.outputs.src-changes == 'true' || needs.eval-changes.outputs.test-changes == 'true' || needs.eval-changes.outputs.ci-changes == 'true'
    needs:
      - eval-changes

    env:
      TEST_CONTAINER_TAG: psr-publish-action:latest

    steps:
      - name: Setup | Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          fetch-depth: 1
          ref: ${{ github.sha }}

      - name: Build | Action Container
        id: container-builder
        uses: docker/build-push-action@1dc73863535b631f98b2378be8619f83b136f4a0  # v6.17.0
        with:
          context: ./src
          load: true # add to `docker images`
          push: false
          platforms: linux/amd64
          tags: ${{ env.TEST_CONTAINER_TAG }}

      - name: Test | Action Container
        run: bash tests/run.sh
